.dockerignore, Dockerfile, src/app.js
- Ignore files in `.dockerignore`
- Change base Image 
#6
=> Lightweight Docker Images

package-lock.json, package.json, src/app.js
=> Resolve #13 Body Parser

.github/workflows/nodejs-tests.yml
This reverts commit b7ec88d93e713d4ace4e6d38ed44c4a9b02f9438.
=> Revert SonarCloud Integration (#24)

src/app.js
=> X-Powered-By Header

README.md, docs/index.md, docs/pages/includes/section-configuration.md, docs/pages/includes/section-tests.md, src/app.js, src/middlewares/customResponseTime.js, test/custom.time.js
=> Personalize response time

README.md, codecov.yml, docs/pages/includes/section-configuration.md, docs/pages/includes/section-tests.md, src/app.js, src/global.json, src/middlewares/showFileMiddleware.js, test/file.js
=> File and directory

README.md, docs/pages/includes/section-tests.md, src/global.json, src/middlewares/customHttpBodyMiddleware.js, src/middlewares/customHttpCodeMiddleware.js, src/middlewares/customHttpEnvBodyMiddleware.js, src/middlewares/customResponseTime.js, src/middlewares/showFileMiddleware.js, test/custom.body.js, test/custom.code.js, test/custom.environment.js, test/custom.js, test/custom.time.js, test/file.js
Change of header name to comply with RFC 2616
Ref : https://github.com/Ealenn/charts/issues/29
=> HTTP Headers

README.md, docs/pages/includes/section-configuration.md, docs/pages/includes/section-tests.md, src/global.json, src/middlewares/customHttpCodeMiddleware.js, test/custom.code.js
=> Randomize status code

.github/workflows/docker-build.yml, .github/workflows/docker-buildx.yml, Dockerfile, README.md, docker-compose.yaml
Docker OS/ARCH #43  :
- linux/amd64
- linux/arm/v6
- linux/arm/v7
- linux/arm64
- linux/386
Follow @kyounger fork
=> Docker Build Arch

README.md, docs/index.md, docs/pages/includes/section-configuration.md, docs/pages/includes/section-tests.md, src/app.js, src/global.json, src/middlewares/customHttpHeadersMiddleware.js, test/custom.headers.js
Customize Responses Headers #42
=> Custom Response Header

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
=> Contributing & Pull Request

docs/index.md, docs/pages/docker-compose.md, docs/pages/docker.md, docs/pages/includes/section-tests.md, docs/pages/kubernetes.md
The documentation is really good. I just spotted some small typos.
No related issue
I like this guy and this project!
not tested
=> [Doc] Fix some minor en language specifics

.github/workflows/docker.yml, .github/workflows/nodejs-tests.yml, Dockerfile, README.md, docs/index.md, docs/pages/includes/section-tests.md, package-lock.json, package.json, src/global.json, src/middlewares/customResponseTime.js
- Enhancement Documentation 
- Update Deprecated packages #56 
- Custom Response Time Validations #55
| ENVIRONMENT                | CLI                       | Default  |
|----------------------------|---------------------------| ---------|
| CONTROLS__TIMES__MIN       | --controls:times:min      | `0`      |
| CONTROLS__TIMES__MAX       | --controls:times:max      | `30000`  |
#56 : Audit Fix
#55 : Custom validations `global.json` : Times Limits
Unit Tests
=> Documentation, Docker Arch and TimeOut Response Time

docs/pages/configuration/loggers.md, docs/pages/quick-start/docker-compose.md, docs/pages/quick-start/docker.md, docs/pages/quick-start/includes/section-examples.md, docs/pages/quick-start/nodejs.md
=> Broken Links

Dockerfile, package-lock.json
=> feat(dependencies): update

.github/workflows/docker.yml, .github/workflows/nodejs-tests.yml
Related to https://github.com/Ealenn/LarbinBot/issues/24#issue-1084219315
=> fix(github): actions checkout version

.github/workflows/gh-page.yml
=> fix(page): rebuild documentation

codecov.yml, docs/Gemfile.lock, package-lock.json, src/app.js, src/webserver.js
=> feat: graceful shutdown on SIGTERM signal

package-lock.json, package.json
Upgrade NPM packages, related to https://github.com/Ealenn/Echo-Server/issues/108
=> fix: upgrade npm packages

src/app.js
Typo fix in src/app.js
Punctuation concerns
Regression test
=> fix(src/app.js): typo fix

.github/workflows/github-bump.yml
Related to https://github.com/Ealenn/Echo-Server/issues/98
=> feat: auto github release

src/app.js
Related to https://github.com/Ealenn/Echo-Server/issues/149
=> feat: parser jsonld
